[build-system]
requires = ["setuptools>=45", "wheel", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "urx"
version = "0.11.0"
description = "Python library to control an UR robot - modified by Acrylic Robotics"
readme = "README.md"
license = {text = "GNU Lesser General Public License v3"}
authors = [
    {name = "Walker Singleton", email = "walker@acrylicrobotics.com"}
]
requires-python = ">=3.6"
dependencies = [
    "numpy",
    "math3d",
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: System :: Hardware :: Hardware Drivers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/oroulet/python-urx"

[tool.setuptools.packages.find]
where = ["."]
include = ["urx*"]
